const Equipe = [
  {
    name: "Metheus",
    role: "Desenvolvedor",
    image: "/api/placeholder/150/150",
    github: "https://github.com/matheualan",
    linkedin: "https://www.linkedin.com/in/matheualan/",
    bio: "Desenvolvedor apaixonado por tecnologia, movido por desafios e aprendizado constante. Busco criar soluções eficientes que gerem valor e impacto positivo para as pessoas.",
  },
  {
    name: "Fernanda Paoleschi Santos",
    role: "Desenvolvedora (Full Stack em formação)",
    image: "/api/placeholder/150/150",
    github: "https://github.com/fernandapaoleschi",
    linkedin: "https://www.linkedin.com/in/fernanda-paoleschi/",
    bio: "Estudante de Engenharia Eletrônica com interesse em desenvolvimento full stack. Tenho experiência em projetos colaborativos e aplicações web, valorizando organização, trabalho em equipe e responsabilidade nas entregas.",
  },
  {
    name: "Tacila",
    role: "Desenvolvedora Full Stack",
    image: "/api/placeholder/150/150",
    github: "https://github.com/Tacila-Souza",
    linkedin: "https://www.linkedin.com/in/tacila-souza/",
    bio: "Atuo no desenvolvimento de soluções Full Stack, transformando requisitos de negócio em software funcional e bem estruturado. Tenho vivência em projetos reais e times ágeis, com atuação como Scrum Master e liderança, além de documentação técnica e versionamento.",
  },
  {
    name: "Alissa",
    role: "Desenvolvedora",
    image: "/api/placeholder/150/150",
    github: "https://github.com/alissasousadev",
    linkedin: "https://www.linkedin.com/in/alissasousa/",
    bio: "Sou apaixonada por tecnologia e por transformar ideias em soluções funcionais. Gosto de aprender na prática, colaborar em equipe e encarar desafios que me façam evoluir, criando sistemas organizados, úteis e que façam a diferença.",
  },
  {
    name: "Felipe",
    role: "Desenvolvedor",
    image: "/api/placeholder/150/150",
    github: "https://github.com/Felipe-GR98",
    linkedin: "https://www.linkedin.com/in/felipegon%C3%A7alves98/",
    bio: "Sou apaixonado por tecnologia e por aprender coisas novas. Gosto de praticar constantemente, participar de projetos em grupo e colaborar com pessoas que compartilham do mesmo entusiasmo por desenvolvimento.",
  },
  {
    name: "Jessica Gizela",
    role: "Desenvolvedora Full Stack",
    image: "/api/placeholder/150/150",
    github: "https://github.com/Jessgi",
    linkedin: "https://www.linkedin.com/in/jessica-gizela-137333349/",
    bio: "Desenvolvedora Full Stack em transição de carreira, com experiência prática em projetos end-to-end. Trago visão de produto e análise para transformar necessidades do negócio em soluções organizadas e focadas na experiência do usuário. Gosto de colaborar, documentar bem e evoluir continuamente.",
  },
]
export default Equipe;